# Generated by Django 5.1.4 on 2024-12-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_scoreboard_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='scoreboard',
        ),
    ]
